version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: monster_battle_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: monster_battle
    volumes:
      - mongo_data:/data/db
    networks:
      - monster_battle_network

networks:
  monster_battle_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
